"""Reporting helpers for single-run evaluations and multi-algorithm comparisons."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


def _bucket(
    value: float,
    *,
    good: float,
    acceptable: float,
    higher_is_better: bool = True,
) -> str:
    """Return a qualitative bucket for a scalar metric."""
    if higher_is_better:
        if value >= good:
            return "strong"
        if value >= acceptable:
            return "moderate"
        return "weak"
    if value <= good:
        return "strong"
    if value <= acceptable:
        return "moderate"
    return "weak"


def _top_zernike_terms(
    coefficients: dict[int, float],
    n_terms: int = 5,
) -> list[dict[str, float | int]]:
    """Return the strongest Zernike terms by absolute magnitude."""
    ranked = sorted(coefficients.items(), key=lambda item: abs(item[1]), reverse=True)
    return [
        {"noll_index": int(index), "coefficient_rad": float(value)}
        for index, value in ranked[:n_terms]
    ]


def _infer_data_regime(source_kind: str) -> str:
    """Map source metadata into a coarse data-regime label."""
    if source_kind == "fits":
        return "real"
    if source_kind in {"npy", "synthetic", "synthetic-test"} or source_kind.startswith("synthetic"):
        return "synthetic"
    return source_kind


def _build_limitations(
    *,
    data_regime: str,
    psf_metadata: dict[str, Any],
    pupil_summary: dict[str, Any],
) -> list[str]:
    """Build explicit limitations for reports so claims stay evidence-backed."""
    limitations = [
        (
            "Results are generated by the repository's internal forward model and "
            "should be interpreted as software-evaluation outputs unless validated "
            "against external instrument-calibrated baselines."
        )
    ]
    if data_regime == "real":
        limitations.append(
            "Real-data reconstructions remain sensitive to centering, background "
            "subtraction, pupil mismatch, and detector systematics."
        )
    if str(psf_metadata.get("source_kind", "")) == "fits":
        limitations.append(
            "This report reflects one preprocessing path and does not, by itself, "
            "establish scientific uncertainty bounds or instrument-grade calibration."
        )
    if pupil_summary.get("approximate_model", True):
        limitations.append(
            "The pupil and detector models are simplified approximations and may not "
            "capture all telescope- or detector-specific effects."
        )
    return limitations


def _validated_claims(
    *,
    data_regime: str,
    psf_metadata: dict[str, Any],
    metrics: dict[str, Any],
) -> list[str]:
    """Return claims supported by current evidence."""
    claims = [
        "The repository records preprocessing provenance and machine-readable outputs.",
        "Internal synthetic and regression-style metrics support software comparison workflows.",
    ]
    if metrics.get("uncertainty"):
        claims.append("Perturbation-based confidence intervals are available for reported metrics.")
    if data_regime == "synthetic":
        claims.append(
            "Synthetic runs can be compared against known-truth phase on benchmark cases."
        )
    if "quality_mask" in psf_metadata:
        claims.append("Real-data preprocessing includes explicit quality-mask diagnostics.")
    if metrics.get("reference_validation"):
        claims.append(
            "Selected instrument/filter combinations can be compared against "
            "curated STScI reference baselines."
        )
    return claims


def _experimental_features(data_regime: str, pupil_summary: dict[str, Any]) -> list[str]:
    """Return features that should still be treated as experimental."""
    features = []
    if pupil_summary.get("bandwidth_fraction", 0.0) or pupil_summary.get("spectral_samples", 1) > 1:
        features.append(
            "Polychromatic forward modeling is approximate and not instrument-calibrated."
        )
    if pupil_summary.get("field_defocus_waves", 0.0):
        features.append("Field-dependent defocus support is a simplified modeling hook.")
    if data_regime == "real":
        features.append(
            "Scientific conclusions on real data remain model- and preprocessing-dependent."
        )
    return features


def build_evaluation_payload(
    *,
    psf_metadata: dict[str, Any],
    algorithm_name: str,
    algorithm_config: dict[str, Any],
    pupil_summary: dict[str, Any],
    metrics: dict[str, Any],
    zernike_coefficients: dict[int, float],
) -> dict[str, Any]:
    """Build a machine-readable single-run evaluation payload."""
    source_kind = str(psf_metadata.get("source_kind", "unknown"))
    data_regime = _infer_data_regime(source_kind)

    ssim = float(metrics.get("ssim", 0.0))
    radial_error = float(metrics.get("radial_profile_error", 0.0))
    ee_error = float(metrics.get("encircled_energy_error", 0.0))
    strehl = float(metrics.get("strehl_ratio", 0.0))
    rms_phase = float(metrics.get("rms_phase_rad", 0.0))

    interpretation = {
        "ssim": _bucket(ssim, good=0.98, acceptable=0.93, higher_is_better=True),
        "radial_profile_error": _bucket(
            radial_error,
            good=0.05,
            acceptable=0.15,
            higher_is_better=False,
        ),
        "encircled_energy_error": _bucket(
            ee_error,
            good=0.01,
            acceptable=0.03,
            higher_is_better=False,
        ),
        "strehl_ratio": _bucket(strehl, good=0.8, acceptable=0.5, higher_is_better=True),
        "rms_phase_rad": _bucket(
            rms_phase,
            good=0.2,
            acceptable=0.5,
            higher_is_better=False,
        ),
    }

    limitations = _build_limitations(
        data_regime=data_regime,
        psf_metadata=psf_metadata,
        pupil_summary=pupil_summary,
    )
    evidence = {
        "validation_scope": (
            "internal synthetic benchmarks"
            if data_regime == "synthetic"
            else "single-run metrics with preprocessing provenance"
        ),
        "preprocessing_recorded": bool(psf_metadata.get("preprocessing")),
        "quality_mask_recorded": "quality_mask" in psf_metadata,
        "uncertainty_recorded": bool(metrics.get("uncertainty")),
        "reference_baseline_recorded": bool(metrics.get("reference_validation")),
        "limitations_count": len(limitations),
    }
    validated_claims = _validated_claims(
        data_regime=data_regime,
        psf_metadata=psf_metadata,
        metrics=metrics,
    )
    experimental_features = _experimental_features(data_regime, pupil_summary)

    return {
        "report_type": "single_run_evaluation",
        "generated_at": datetime.now(UTC).isoformat(),
        "data_regime": data_regime,
        "algorithm": algorithm_name,
        "algorithm_config": algorithm_config,
        "source": psf_metadata,
        "pupil": pupil_summary,
        "metrics": metrics,
        "interpretation": interpretation,
        "evidence": evidence,
        "limitations": limitations,
        "validated_claims": validated_claims,
        "experimental_features": experimental_features,
        "top_zernike_terms": _top_zernike_terms(zernike_coefficients),
    }


def render_evaluation_markdown(payload: dict[str, Any]) -> str:
    """Render a paper-style Markdown summary for a single run."""
    metrics = payload["metrics"]
    source = payload["source"]
    interpretation = payload["interpretation"]
    evidence = payload["evidence"]
    uncertainty = metrics.get("uncertainty", {})
    reference_validation = metrics.get("reference_validation", {})

    observation_id = source.get("header", {}).get(
        "ROOTNAME",
        source.get("obs_id", "unknown"),
    )
    filter_name = source.get("header", {}).get(
        "FILTER",
        source.get("header", {}).get("FILTER2", "unknown"),
    )
    title = (
        "# Real-Data Evaluation Report"
        if payload["data_regime"] == "real"
        else "# Evaluation Report"
    )

    lines = [
        title,
        "",
        "## Abstract",
        "",
        f"This report summarises one `{payload['algorithm']}` reconstruction on a "
        f"`{payload['data_regime']}` dataset. The metrics here are useful for "
        "regression tracking and internal validation, but they are not a substitute "
        "for external scientific validation.",
        "",
        "## Data",
        "",
        f"- Source kind: `{source.get('source_kind', 'unknown')}`",
        f"- Source file: `{source.get('source_filename', 'unknown')}`",
        f"- Observation ID: `{observation_id}`",
        f"- Filter: `{filter_name}`",
        f"- Preprocessing: {', '.join(source.get('preprocessing', [])) or 'not recorded'}",
        "",
        "## Method",
        "",
        f"- Algorithm: `{payload['algorithm']}`",
        f"- Max iterations: `{payload['algorithm_config'].get('max_iterations', 'unknown')}`",
        f"- Noise model: `{payload['algorithm_config'].get('noise_model', 'unknown')}`",
        f"- Momentum: `{payload['algorithm_config'].get('momentum', 'unknown')}`",
        "",
        "## Quantitative Results",
        "",
        (
            f"- Strehl ratio: **{metrics.get('strehl_ratio', 0.0):.4f}** "
            f"({interpretation['strehl_ratio']})"
        ),
        (
            f"- RMS phase error: **{metrics.get('rms_phase_rad', 0.0):.4f} rad** "
            f"({interpretation['rms_phase_rad']})"
        ),
        f"- SSIM: **{metrics.get('ssim', 0.0):.4f}** ({interpretation['ssim']})",
        (
            "- Radial-profile error: "
            f"**{metrics.get('radial_profile_error', 0.0):.4f}** "
            f"({interpretation['radial_profile_error']})"
        ),
        (
            "- Encircled-energy error: "
            f"**{metrics.get('encircled_energy_error', 0.0):.4f}** "
            f"({interpretation['encircled_energy_error']})"
        ),
        f"- Iterations: **{metrics.get('n_iterations', 0)}**",
        f"- Elapsed time: **{metrics.get('elapsed_seconds', 0.0):.3f} s**",
        "",
        "## Evidence",
        "",
        f"- Validation scope: `{evidence['validation_scope']}`",
        f"- Preprocessing provenance recorded: `{evidence['preprocessing_recorded']}`",
        f"- Quality mask metadata recorded: `{evidence['quality_mask_recorded']}`",
        f"- Uncertainty summary recorded: `{evidence['uncertainty_recorded']}`",
        f"- External reference baseline recorded: `{evidence['reference_baseline_recorded']}`",
        "",
        "## Dominant Zernike Terms",
        "",
        "| Noll index | Coefficient (rad) |",
        "|-----------:|------------------:|",
    ]
    lines.extend(
        [
            f"| {term['noll_index']} | {term['coefficient_rad']:.4f} |"
            for term in payload["top_zernike_terms"]
        ]
    )

    lines.extend(
        [
            "",
            "## Limitations",
            "",
        ]
    )
    lines.extend([f"- {item}" for item in payload["limitations"]])
    if uncertainty:
        strehl_ci = uncertainty.get("summary", {}).get("strehl_ratio", {}).get("ci95", [0.0, 0.0])
        rms_ci = uncertainty.get("summary", {}).get("rms_phase_rad", {}).get("ci95", [0.0, 0.0])
        lines.extend(
            [
                "",
                "## Uncertainty Summary",
                "",
                f"- Samples: **{uncertainty.get('n_samples', 0)}**",
                f"- Strehl 95% CI: `{strehl_ci}`",
                f"- RMS phase 95% CI: `{rms_ci}`",
            ]
        )
    if reference_validation:
        baseline = reference_validation.get("baseline", {})
        observed = reference_validation.get("observed", {})
        reconstructed = reference_validation.get("reconstructed", {})
        deviations = reference_validation.get("deviations", {})
        lines.extend(
            [
                "",
                "## External Reference Baseline",
                "",
                f"- Baseline key: `{baseline.get('key', 'unknown')}`",
                (
                    f"- Citation: [{baseline.get('citation_title', 'reference')}]"
                    f"({baseline.get('citation_url', '')})"
                ),
                f"- Notes: {baseline.get('notes', 'n/a')}",
            ]
        )
        if observed:
            lines.append(
                f"- Observed FWHM / EE: `{observed.get('fwhm_arcsec', 'n/a')}` arcsec, "
                f"`{observed.get('encircled_energy_fraction', 'n/a')}`"
            )
        if reconstructed:
            lines.append(
                f"- Reconstructed FWHM / EE: `{reconstructed.get('fwhm_arcsec', 'n/a')}` arcsec, "
                f"`{reconstructed.get('encircled_energy_fraction', 'n/a')}`"
            )
        if deviations:
            lines.append(f"- Deviations: `{deviations}`")
    lines.extend(
        [
            "",
            "## Supported Claims",
            "",
        ]
    )
    lines.extend([f"- {item}" for item in payload["validated_claims"]])
    if payload["experimental_features"]:
        lines.extend(
            [
                "",
                "## Experimental Features",
                "",
            ]
        )
        lines.extend([f"- {item}" for item in payload["experimental_features"]])
    lines.extend(
        [
            "",
            "## Reproducibility",
            "",
            "All quantitative values in this report are mirrored in machine-readable "
            "JSON artifacts so results can be compared across commits, datasets, and "
            "algorithms.",
            "",
        ]
    )
    return "\n".join(lines)


def write_evaluation_report(
    payload: dict[str, Any],
    output_dir: Path,
    stem: str = "evaluation_report",
) -> dict[str, Path]:
    """Persist single-run evaluation reports as JSON and Markdown."""
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = output_dir / f"{stem}.json"
    md_path = output_dir / f"{stem}.md"
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    md_path.write_text(render_evaluation_markdown(payload), encoding="utf-8")
    return {"json": json_path, "markdown": md_path}


def build_comparison_payload(
    *,
    source_metadata: dict[str, Any],
    summaries: list[dict[str, Any]],
    artifacts: dict[str, str] | None = None,
) -> dict[str, Any]:
    """Build a machine-readable comparison payload for one dataset across algorithms."""
    ranked = sorted(
        summaries,
        key=lambda row: (
            -float(row.get("ssim", 0.0)),
            float(row.get("radial_profile_error", 0.0)),
            float(row.get("encircled_energy_error", 0.0)),
        ),
    )
    return {
        "report_type": "comparison_report",
        "generated_at": datetime.now(UTC).isoformat(),
        "source": source_metadata,
        "ranked_results": ranked,
        "best_algorithm": ranked[0]["algorithm"] if ranked else None,
        "artifacts": artifacts or {},
        "reference_baseline": next(
            (
                row.get("reference_validation", {})
                for row in ranked
                if row.get("reference_validation")
            ),
            {},
        ),
        "limitations": [
            "Algorithm ranking is based on internal image-fidelity metrics and does "
            "not by itself establish scientific correctness on real telescope data."
        ],
    }


def render_comparison_markdown(payload: dict[str, Any]) -> str:
    """Render a paper-style comparison report in Markdown."""
    lines = [
        "# Multi-Algorithm Evaluation Report",
        "",
        "## Abstract",
        "",
        "This report compares multiple retrieval algorithms on a single observation "
        "using shared fidelity and convergence metrics. It is best interpreted as "
        "internal comparative evidence rather than a definitive scientific ranking.",
        "",
        "## Data",
        "",
        f"- Source file: `{payload['source'].get('source_filename', 'unknown')}`",
        f"- Source kind: `{payload['source'].get('source_kind', 'unknown')}`",
        f"- Best algorithm by ranking: `{payload.get('best_algorithm', 'n/a')}`",
        "",
        "## Results",
        "",
        ("| Rank | Algorithm | SSIM | Strehl | RMS phase (rad) | Radial err | EE err | Time (s) |"),
        "|-----:|-----------|-----:|-------:|----------------:|-----------:|-------:|---------:|",
    ]
    lines.extend(
        [
            (
                f"| {idx} | {row['algorithm']} | {row['ssim']:.4f} | "
                f"{row['strehl_ratio']:.4f} | {row['rms_phase_rad']:.4f} | "
                f"{row['radial_profile_error']:.4f} | "
                f"{row['encircled_energy_error']:.4f} | "
                f"{row['elapsed_seconds']:.3f} |"
            )
            for idx, row in enumerate(payload["ranked_results"], start=1)
        ]
    )
    if payload.get("reference_baseline"):
        baseline = payload["reference_baseline"].get("baseline", {})
        lines.extend(
            [
                "",
                "## External Reference Baseline",
                "",
                f"- Baseline key: `{baseline.get('key', 'unknown')}`",
                (
                    f"- Citation: [{baseline.get('citation_title', 'reference')}]"
                    f"({baseline.get('citation_url', '')})"
                ),
            ]
        )
    if payload.get("artifacts"):
        lines.extend(
            [
                "",
                "## Comparison Plots",
                "",
            ]
        )
        lines.extend([f"- `{key}`: `{value}`" for key, value in payload["artifacts"].items()])
    lines.extend(
        [
            "",
            "## Limitations",
            "",
        ]
    )
    lines.extend([f"- {item}" for item in payload.get("limitations", [])])
    lines.append("")
    return "\n".join(lines)


def write_comparison_report(
    payload: dict[str, Any],
    output_dir: Path,
    stem: str = "comparison_report",
) -> dict[str, Path]:
    """Persist comparison reports as JSON and Markdown."""
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = output_dir / f"{stem}.json"
    md_path = output_dir / f"{stem}.md"
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    md_path.write_text(render_comparison_markdown(payload), encoding="utf-8")
    return {"json": json_path, "markdown": md_path}
